### ISSUE TITLE
Build fails with `spawn EINVAL`

### ISSUE THREAD

**Issue by derevnjuk** [prebuild/node-gyp-build#68]
**Environment**
- Node.js Version: 18, 20
- Platform: Windows x86

**Description**
The build process fails with an `EINVAL` error during the `spawn` operation in `node-gyp-build`. This issue seems to affect only Windows x86 configurations. A similar problem has been reported in `prebuildify`: prebuild/prebuildify#83.

**Steps to Reproduce**
1. Run the `node-gyp-build` in a Windows x86 environment using Node.js versions 18 or 20.
2. Observe the failure in the build process.

**Expected Behavior**
The build should complete without errors.

**Actual Behavior**
The build process fails and outputs the following error:

```
> node-gyp-build

node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:[11](https://github.com/NeuraLegion/node-raw-socket/actions/runs/8686906219/job/23819333405#step:4:12))
    at Object.spawn (node:child_process:761:9)
    at build (D:\a\node-raw-socket\node-raw-socket\node_modules\node-gyp-build\bin.js:30:8)
    at preinstall (D:\a\node-raw-socket\node-raw-socket\node_modules\node-gyp-build\bin.js:39:32)
    at D:\a\node-raw-socket\node-raw-socket\node_modules\node-gyp-build\bin.js:11:7
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:[16](https://github.com/NeuraLegion/node-raw-socket/actions/runs/8686906219/job/23819333405#step:4:17))
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

```

**Comment by derevnjuk** [comment]
@mafintosh, do you have any updates on this? Could you please review the PR?
